### ISSUE TITLE
Determine which types should be interpreted as False Values, Non-False Values, Empty Lists, Non-Empty Lists and Lambdas according to Mustache Section specification.

### ISSUE THREAD

**Issue by ylepikhov** [sviperll/static-mustache#2] opened 2014-12-30 14:57 UTC
See [spec](http://mustache.github.io/mustache.5.html#Sections).

**Comment by sviperll** [comment] 2015-01-04 13:13
I'll consider this to be duplicate of #4

**Closed as completed by sviperll** 2015-01-04 13:13 UTC
